- name: virtostart-dentalstoredemo
  gitops: true
  production: false
  servicePlan: B1
  platform:
    dbProvider: AzureSQL Database
    imageRepository: virtopaasregistrymain.azurecr.io/virtostart/platform
    imageTag: 3.851.0-379f819a1
    sqlReplica: false
    config:
      APPINSIGHTS_INSTRUMENTATIONKEY: 26f3faa1-f3fb-4bd4-aff4-89d7241cf249
      reboot: 3
  storefront:
    enabled: false
    imageRepository: virtopaasregistrymain.azurecr.io/virtostart/storefront
    imageTag: 6.0
    themes:
      Dental-store: https://github.com/VirtoCommerce/vc-frontend/releases/download/2.6.0/vc-theme-b2b-vue-2.6.0.zip
  ingress: {}
  customApps:
    app1:
      enabled: false
    app2:
      enabled: false
  routes:
  - host: dentalstoredemo.govirto.com
    root: Dental-store
    paths:
    - path: /xapi
      route: platform
    - path: /files
      route: platform
    - path: /connect/token
      route: platform
    - path: /graphql
      route: platform
    - path: /revoke/token
      route: platform
    - path: /api/files
      route: platform
    - path: /externalsignin
      route: platform
    - path: /signin-oidc
      route: platform
    - path: /signin-google
      route: platform
  version: 3.219
